version: '2'

services:
  mattermost:
    image: mattermost/platform
    labels:
      - 'traefik.backend=mattermost'
      - 'traefik.port=8065'
      - 'traefik.frontend.rule=Host:matter.docker.localhost'

  traefik:
    image: traefik:1.4.1
    command: -c /dev/null --web --docker --docker.domain=docker.localhost --logLevel=DEBUG
    ports:
      - '80:80'
      - '8080:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

